In [2]:
import numpy as np

In [28]:
np.pi

3.141592653589793

# np.array

### Defintion of arrays

In [3]:
x = np.zeros(2)
y = np.ones((3,2))

#from a list
listeVector = [1,3,2]
zVec = np.array(listeVector)


listeMat = [[1,3,2],[5,19,-3]]
zMat = np.array(listeMat)

print(x,y,zVec,zMat)

[ 0.  0.] [[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]] [1 3 2] [[ 1  3  2]
 [ 5 19 -3]]


In [ ]:
a = np.linspace(0, 23, 24)  # tableau de z elements, entre x et y.
b = np.arange(0,24,1)       # Si on avait mis 24. , on aurait créé des floats

In [22]:
# Vectorize an array
print(zMat.ravel())

[ 1  3  2  5 19 -3]


#### Manipulation des arrays

In [24]:
a[0:2, 1] #each row in the second column

array([ 3, 19])

In [25]:
np.vstack((a,b))
np.hstack((a,b))
np.concatenate((a,b), axis=0)
a.flat[:]
a.ravel()
a.reshape(2,3)

array([[  1.00000000e+00,   3.00000000e+00,   2.00000000e+00],
       [  5.00000000e+00,   1.90000000e+01,  -3.00000000e+00],
       [  2.71828183e+00,   2.00855369e+01,   7.38905610e+00],
       [  1.48413159e+02,   1.78482301e+08,   4.97870684e-02]])

In [ ]:
print(np.tile(a, (4, 1))) #repmat

### Methodes

In [31]:
print(a.shape)
print(a.size)

(2, 3)
6


### Random

In [ ]:
a = np.random.seed(293423)
B = np.random.random_integers(0, 100, (3, 3))	# randint fait pareil
c = np.random.normal(0, 1, (3, 3)) 		#matrices aleatoires d'une distribution normale

In [ ]:
a=np.random.permutation(c)


### Conditions

In [7]:
a = np.array([-1,2,7,19])
print(np.logical_and(a>0,a<10))
np.where(a != 0, 1 / a, a)	#condition, on fait quelque chose
np.isnan(a)
np.isfinite(a)

[False  True  True False]


In [32]:
a.clip(0, 5)

array([[1, 3, 2],
       [5, 5, 0]])

### Operations

In [20]:
b=np.exp(a)
np.dot(A,B)  # multiplication matrice
np.linalg.inv(a)
np.linalg.solve(a, y)
np.linalg.eig(j)

NameError: name 'A' is not defined

In [21]:
np.floor(a/10)

array([[ 0.,  0.,  0.],
       [ 0.,  1., -1.]])

<font color='red'>  Operations on str (get real name) </font>

Min, max

In [9]:
a = np.array([[1,3,2],[5,19,-3]])
print(a)
print(a.min())
print(a.min(0))
print(a.min(1))

[[ 1  3  2]
 [ 5 19 -3]]
-3
[ 1  3 -3]
[ 1 -3]


In [ ]:
a.sort()
a.transpose()	#a.T

In [17]:
a = np.array([[1,3,2],[5,19,-3]])
print(a.cumsum(axis=1))
print(a.prod())

[[ 1  4  6]
 [ 5 24 21]]
-1710
